# Generated by Django 6.0.4 on 2026-04-27 16:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AssistantUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InstructorUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StudentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('monday', models.BooleanField(default=False)),
                ('tuesday', models.BooleanField(default=False)),
                ('wednesday', models.BooleanField(default=False)),
                ('thursday', models.BooleanField(default=False)),
                ('friday', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=50)),
                ('user_type', models.CharField(choices=[('ADMIN', 'ADMIN'), ('TA', 'TA'), ('STUDENT', 'STUDENT'), ('INSTRUCTOR', 'INSTRUCTOR')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseCode', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)])),
                ('courseName', models.CharField(max_length=20)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='scheduler_app.department')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseName', models.CharField(max_length=20)),
                ('TAOfficeHoursApproved', models.BooleanField(default=False)),
                ('Instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler_app.instructoruser')),
                ('TA', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler_app.assistantuser')),
                ('InstructorOfficeHours', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecture_instructor_hours', to='scheduler_app.timeslot')),
                ('MeetingTimes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecture_meeting_times', to='scheduler_app.timeslot')),
                ('TAOfficeHours', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecture_ta_hours', to='scheduler_app.timeslot')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionCode', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)])),
                ('section_type', models.CharField(choices=[('LECTURE', 'LECTURE'), ('LAB', 'LAB'), ('DISCUSSION', 'DISCUSSION')], default='LECTURE', max_length=20)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='scheduler_app.course')),
                ('timeslot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='scheduler_app.timeslot')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='scheduler_app.user')),
                ('ta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections_assisting', to='scheduler_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='OfficeHourReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservationDate', models.DateField()),
                ('reservedAt', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_hour_reservations', to='scheduler_app.course')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_hour_reservations', to='scheduler_app.timeslot')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_hour_reservations_received', to='scheduler_app.user')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_hour_reservations_made', to='scheduler_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='OfficeHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_hours', to='scheduler_app.course')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_hours', to='scheduler_app.timeslot')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_hours_given', to='scheduler_app.user')),
            ],
        ),
    ]
