# Generated by Django 6.0.3 on 2026-04-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officehour',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('INSTRUCTOR', 'INSTRUCTOR'), ('STUDENT', 'STUDENT'), ('TA', 'TA')], max_length=20),
        ),
    ]
