# Generated by Django 6.0.4 on 2026-04-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0002_officehour_approved_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('TA', 'TA'), ('STUDENT', 'STUDENT'), ('INSTRUCTOR', 'INSTRUCTOR')], max_length=20),
        ),
    ]
