# Generated by Django 6.0.4 on 2026-05-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_sections', to='scheduler_app.user'),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('LECTURE', 'LECTURE'), ('DISCUSSION', 'DISCUSSION'), ('LAB', 'LAB')], default='LECTURE', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('INSTRUCTOR', 'INSTRUCTOR'), ('TA', 'TA'), ('ADMIN', 'ADMIN'), ('STUDENT', 'STUDENT')], max_length=20),
        ),
    ]
