# Generated by Django 6.0.4 on 2026-05-20 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0004_section_students_alter_section_section_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('LAB', 'LAB'), ('DISCUSSION', 'DISCUSSION'), ('LECTURE', 'LECTURE')], default='LECTURE', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('STUDENT', 'STUDENT'), ('ADMIN', 'ADMIN'), ('INSTRUCTOR', 'INSTRUCTOR'), ('TA', 'TA')], max_length=20),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('chunk_start_time', models.TimeField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESSFUL', 'SUCCESSFUL'), ('TARDY', 'TARDY')], default='PENDING', max_length=20)),
                ('office_hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='scheduler_app.officehour')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='scheduler_app.user')),
            ],
            options={
                'unique_together': {('office_hour', 'date', 'chunk_start_time')},
            },
        ),
    ]
