# Generated by Django 6.0.4 on 2026-05-21 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0005_alter_section_section_type_alter_user_user_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESSFUL', 'SUCCESSFUL'), ('TARDY', 'TARDY'), ('NO_SHOW', 'NO_SHOW')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('LECTURE', 'LECTURE'), ('DISCUSSION', 'DISCUSSION'), ('LAB', 'LAB')], default='LECTURE', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('STUDENT', 'STUDENT'), ('TA', 'TA'), ('ADMIN', 'ADMIN'), ('INSTRUCTOR', 'INSTRUCTOR')], max_length=20),
        ),
    ]
