# Generated by Django 6.0.4 on 2026-05-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0006_alter_reservation_status_alter_section_section_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('LECTURE', 'LECTURE'), ('LAB', 'LAB'), ('DISCUSSION', 'DISCUSSION')], default='LECTURE', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('INSTRUCTOR', 'INSTRUCTOR'), ('TA', 'TA'), ('STUDENT', 'STUDENT')], max_length=20),
        ),
    ]
